import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "../styles/index.scss";
import SetUpGlobalColors from "./Logic";
import muiTheme from "@/theme/mui";
import { ThemeProvider } from "@emotion/react";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider theme={muiTheme}>
        <body className={inter.className}>{children}</body>
        <SetUpGlobalColors />
      </ThemeProvider>
    </html>
  );
}
